config/routes.rb
Rails.application.routes.draw do

  get    'launchpad/new'  => "launchpad#new"   #, as: :launch
  get    'launchpad/show' => 'launchpad#show'  #, as: :status
  post   'launchpad'      => 'launchpad#create'
  delete 'launchpad'      => 'launchpad#destroy'

  root 'launchpad#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/launchpad_controller.rb
class LaunchpadController < ApplicationController
  def new
    @flavor_options = [['m3.medium', "m3.medium"], ['m3.large', 'm3.large']]
  end

  def create
    options = {
      :image_id   => "#{params['image_id']}",
      :tags       => {'Name' => "#{params['tags']}"},
      :flavor_id  => "#{params['flavor_id']}",
      :groups     => "#{params['groups']}", # this security group must include HTTP protocol
      :user       => 'ubuntu'
    }
    puts options.inspect
    # fail

    LaunchWorker.perform_async('new', options)
    redirect_to launchpad_show_path
  end

  def show
    @instance_id = redis.get("launcher:instance_id")
    @dns_name    = redis.get("launcher:dns_name")
  end

  def destroy
    LaunchWorker.perform_async('destroy', {})
    redirect_to launchpad_new_path, notice: 'Server successfully terminated!'
  end

private
  def redis
    @redis ||= Redis.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/launchpad_helper.rb
module LaunchpadHelper
end

app/views/launchpad/new.html.erb
<h1>Launch Bitnami WordPad server</h1>
<% if flash[:notice] %>
  <p class="flash notice"><%= flash[:notice] %></p>
<% end %>

<%= form_tag(launchpad_path) do %>
  <fieldset>
    <p>
      <%= label_tag :image_id, 'Image Id' %>
      <%= text_field_tag :image_id, 'ami-746c7731', required: true %>
    </p>
    <p>
      <%= label_tag :tags, 'Instance Name' %>
      <%= text_field_tag :tags, 'Bitnami-WordPress' %>
    </p>
    <p>
      <%= label_tag :flavor_id, 'Flavor Id' %>
      <!-- <%= text_field_tag :flavor_id, 'm3.medium' %> -->
      <%= select_tag :flavor_id, options_for_select(@flavor_options) %>
    </p>
    <p>
      <%= label_tag :groups, 'Security Groups' %>
      <%= text_field_tag :groups, 'default', required: true %>
    </p>
    <p>
      <%= submit_tag 'Launch' %>
    </p>
  </fieldset>
<% end %>

app/views/launchpad/show.html.erb
<header>
<h1>Ec2 instance status</h1>
</header>

<% if @instance_id %>
<p>
  <%= link_to "Link to Bitnami WordPress server", "http://#{@dns_name}" %>
</p>
<p>
  <%= link_to 'Terminate server', launchpad_path, method: :delete %>
</p>
<% else %>
<p> <%= "Wait for machine to be booted ..." %> </p>
<% end %>
<p>

</p>

<footer>
  <p>
    <%= link_to 'Refresh', launchpad_show_path %>
  </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniCloudLaunchpad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>